language: python
python:
  - "3.8"
before_install:
  - python --version
install:
  - pip install pipenv
  - pipenv install
  - pip list

before_script:
  - export FLASK_APP=main.py
  - python main.py > /dev/null &

script:
  - pytest